import { useEffect } from "react";
import { Link } from "wouter";
import AppFooter from "@/components/AppFooter";

export default function Terms() {
  useEffect(() => { window.scrollTo({ top: 0 }); }, []);
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col">
      <header className="border-b border-white/5 px-6 py-4">
        <Link href="/" className="text-sm text-zinc-400 hover:text-white transition-colors">← Back to PrepInterv AI</Link>
      </header>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-12 space-y-10">
        <div>
          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-zinc-500 text-sm">Last updated: April 2026</p>
        </div>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">1. Acceptance of terms</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            By accessing or using PrepInterv AI ("the Service"), operated by IvanGold Technologies, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">2. Description of service</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            PrepInterv AI is an AI-powered interview practice platform. It provides simulated interview sessions with AI-generated questions, voice interaction, and automated performance feedback. The Service is intended for practice and educational purposes only.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">3. Not professional advice</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            All interview questions, feedback, scores, and performance reports generated by the Service are produced by artificial intelligence and are for practice purposes only. They do not constitute professional career counselling, HR guidance, or employment advice. IvanGold Technologies makes no guarantee that use of the Service will result in employment outcomes.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">4. AI-generated content</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            Interview questions and performance feedback are generated by AI systems. These outputs are intended for practice and skill development and may not always be fully precise or tailored. Users should interpret the feedback with discretion.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">5. Session recording consent</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            By starting an interview session, you consent to the recording and processing of your audio responses for the purpose of transcription and performance analysis. Recordings are processed by our third-party AI providers and are used solely to deliver the Service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">6. Acceptable use</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not use the Service to submit content that is unlawful, harmful, abusive, or otherwise objectionable, or attempt to reverse-engineer, scrape, or disrupt the platform.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">7. Subscription and billing</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            The Free Trial plan provides one session at no charge. Paid plans (Starter and Pro) are billed monthly. You may cancel your subscription at any time; cancellation takes effect at the end of the current billing period. No refunds are issued for partial billing periods.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">8. Limitation of liability</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            To the maximum extent permitted by applicable law, IvanGold Technologies shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data, loss of revenue, or failure to obtain employment.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">9. Changes to terms</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            We reserve the right to modify these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">10. Contact</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">
            If you have questions about these Terms, contact us at <a href="mailto:hello@prepinterv.com" className="text-primary hover:underline">hello@prepinterv.com</a>.
          </p>
        </section>
      </main>

      <AppFooter />
    </div>
  );
}
